In [1]:
import pandas as pd
import numpy as np

Read the csv file.

In [2]:
df = pd.read_csv('/content/ChurnPrediction (1).csv')

Explore the dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   PastEmployee             1470 non-null   object
 2   BusinessTravel           1470 non-null   object
 3   Department               1470 non-null   object
 4   DistanceFromHome         1470 non-null   int64
 5   Education                1470 non-null   int64
 6   EducationField           1470 non-null   object
 7   EnvironmentSatisfaction  1470 non-null   int64
 8   Gender                   1470 non-null   object
 9   JobInvolvement           1470 non-null   int64
 10  JobLevel                 1470 non-null   int64
 11  JobRole                  1470 non-null   object
 12  JobSatisfaction          1470 non-null   int64
 13  MaritalStatus            1470 non-null   object
 14  MonthlyIncome            1470 non-null   int64
 15  NumCompaniesWorked       1470 non-null   int64
 16  OverTime                 1470 non-null   object
 17  PercentSalaryHike        1470 non-null   int64
 18  PerformanceRating        1470 non-null   int64
 19  StockOptionLevel         1470 non-null   int64
 20  TotalWorkingYears        1470 non-null   int64
 21  TrainingTimesLastYear    1470 non-null   int64
 22  WorkLifeBalance          1470 non-null   int64
 23  YearsAtCompany           1470 non-null   int64
 24  YearsInCurrentRole       1470 non-null   int64
 25  YearsSinceLastPromotion  1470 non-null   int64
 26  YearsWithCurrManager     1470 non-null   int64
dtypes: int64(19), object(8)
memory usage: 310.2+ KB

In [4]:
df

,Age,PastEmployee,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,PercentSalaryHike,PerformanceRating,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,46,No,Travel_Rarely,Human Resources,5,2,Medical,2,Male,3,...,22,4,1,16,2,3,4,2,0,2
1,37,Yes,Travel_Rarely,Human Resources,6,4,Human Resources,3,Male,3,...,22,4,0,7,3,3,3,2,0,2
2,59,No,Non-Travel,Human Resources,2,4,Human Resources,3,Female,2,...,21,4,1,30,3,3,3,2,2,2
3,54,No,Non-Travel,Human Resources,26,3,Human Resources,4,Female,4,...,12,3,0,23,3,3,5,3,4,4
4,26,No,Travel_Rarely,Human Resources,25,1,Life Sciences,3,Female,3,...,23,4,1,8,3,3,8,7,5,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,45,No,Travel_Rarely,Sales,20,3,Life Sciences,4,Female,3,...,15,3,0,8,3,3,5,3,0,1
1466,50,Yes,Travel_Rarely,Sales,28,3,Marketing,4,Male,2,...,13,3,1,20,3,3,3,2,2,0
1467,39,No,Travel_Rarely,Sales,24,1,Marketing,2,Female,2,...,11,3,1,21,2,2,20,9,9,6
1468,26,No,Travel_Rarely,Sales,5,3,Other,4,Female,2,...,18,3,0,5,2,3,4,2,0,0
1469,49,No,Travel_Frequently,Sales,2,3,Medical,4,Male,2,...,14,3,0,17,3,2,9,6,0,8

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

ls = ['PastEmployee','BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','OverTime']

for col in ls:
  df[col] = le.fit_transform(df[col])

In [6]:
df

,Age,PastEmployee,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,PercentSalaryHike,PerformanceRating,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,46,0,2,0,5,2,3,2,1,3,...,22,4,1,16,2,3,4,2,0,2
1,37,1,2,0,6,4,0,3,1,3,...,22,4,0,7,3,3,3,2,0,2
2,59,0,0,0,2,4,0,3,0,2,...,21,4,1,30,3,3,3,2,2,2
3,54,0,0,0,26,3,0,4,0,4,...,12,3,0,23,3,3,5,3,4,4
4,26,0,2,0,25,1,1,3,0,3,...,23,4,1,8,3,3,8,7,5,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,45,0,2,2,20,3,1,4,0,3,...,15,3,0,8,3,3,5,3,0,1
1466,50,1,2,2,28,3,2,4,1,2,...,13,3,1,20,3,3,3,2,2,0
1467,39,0,2,2,24,1,2,2,0,2,...,11,3,1,21,2,2,20,9,9,6
1468,26,0,2,2,5,3,4,4,0,2,...,18,3,0,5,2,3,4,2,0,0
1469,49,0,1,2,2,3,3,4,1,2,...,14,3,0,17,3,2,9,6,0,8

missing value analysis|

In [7]:
df.isnull().sum()

Age                        0
PastEmployee               0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
EnvironmentSatisfaction    0
Gender                     0
JobInvolvement             0
JobLevel                   0
JobRole                    0
JobSatisfaction            0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
OverTime                   0
PercentSalaryHike          0
PerformanceRating          0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
WorkLifeBalance            0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

# Experiment without feature selection

## Separate dependent and independent variables

In [8]:
X = df.drop(columns=['PastEmployee'])
y = df['PastEmployee']

Split data into train and test

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

Write a function for implementing the model

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

Logistic Regression

In [11]:
def LR(X_train, X_test, y_train, y_test):
  logReg = LogisticRegression()
  logReg.fit(X_train, y_train)
  y_pred = logReg.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

Gaussian Naive Bayes Classifier

In [12]:
from sklearn.naive_bayes import GaussianNB

In [13]:
def gaussian(X_train, X_test, y_train, y_test):
  gnb = GaussianNB()
  gnb.fit(X_train, y_train)
  y_pred = gnb.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [15]:
LR(X_train, X_test, y_train, y_test)

[[304   2]
 [ 55   7]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.91       306
           1       0.78      0.11      0.20        62

    accuracy                           0.85       368
   macro avg       0.81      0.55      0.56       368
weighted avg       0.84      0.85      0.79       368

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [16]:
gaussian(X_train, X_test, y_train, y_test)

[[254  52]
 [ 24  38]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.42      0.61      0.50        62

    accuracy                           0.79       368
   macro avg       0.67      0.72      0.68       368
weighted avg       0.83      0.79      0.81       368

## Feature selection using correlation matrix

In [17]:
df.corr()

,Age,PastEmployee,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,PercentSalaryHike,PerformanceRating,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,0.024751,-0.031882,-0.001686,0.208034,-0.040873,0.010146,-0.036311,0.029820,...,0.003634,0.001904,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
PastEmployee,-0.159205,1.000000,0.000074,0.063991,0.077924,-0.031373,0.026846,-0.103369,0.029453,-0.130016,...,-0.013478,0.002889,-0.137145,-0.171063,-0.059478,-0.063939,-0.134392,-0.160545,-0.033019,-0.156199
BusinessTravel,0.024751,0.000074,1.000000,-0.009044,-0.024469,0.000757,0.023724,0.004174,-0.032981,0.039062,...,-0.029377,-0.026341,-0.016727,0.034226,0.015240,-0.011256,-0.014575,-0.011497,-0.032591,-0.022636
Department,-0.031882,0.063991,-0.009044,1.000000,0.017225,0.007996,0.013720,-0.019395,-0.041583,-0.024586,...,-0.007840,-0.024604,-0.012193,-0.015762,0.036875,0.026383,0.022920,0.056315,0.040061,0.034282
DistanceFromHome,-0.001686,0.077924,-0.024469,0.017225,1.000000,0.021042,0.002013,-0.016075,-0.001851,0.008783,...,0.040235,0.027110,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Education,0.208034,-0.031373,0.000757,0.007996,0.021042,1.000000,-0.039592,-0.027128,-0.016547,0.042438,...,-0.011111,-0.024539,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
EducationField,-0.040873,0.026846,0.023724,0.013720,0.002013,-0.039592,1.000000,0.043163,-0.002504,-0.002655,...,-0.011214,-0.005614,-0.016185,-0.027848,0.049195,0.041191,-0.018692,-0.010506,0.002326,-0.004130
EnvironmentSatisfaction,0.010146,-0.103369,0.004174,-0.019395,-0.016075,-0.027128,0.043163,1.000000,0.000508,-0.008278,...,-0.031701,-0.029548,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
Gender,-0.036311,0.029453,-0.032981,-0.041583,-0.001851,-0.016547,-0.002504,0.000508,1.000000,0.017960,...,0.002733,-0.013859,0.012716,-0.046881,-0.038787,-0.002753,-0.029747,-0.041483,-0.026985,-0.030599
JobInvolvement,0.029820,-0.130016,0.039062,-0.024586,0.008783,0.042438,-0.002655,-0.008278,0.017960,1.000000,...,-0.017205,-0.029071,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
JobLevel,0.509604,-0.169105,0.019311,0.101963,0.005303,0.101589,-0.044933,0.001212,-0.039403,-0.012630,...,-0.034730,-0.021222,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
JobRole,-0.122427,0.067151,0.002724,0.662431,-0.001015,0.004236,0.015599,-0.017321,-0.039723,0.006616,...,-0.000848,-0.024233,-0.019171,-0.145439,0.001342,0.027764,-0.083657,-0.028354,-0.046384,-0.041150
JobSatisfaction,-0.004892,-0.103481,-0.033962,0.021001,-0.003669,-0.011296,-0.034401,-0.006784,0.033252,-0.021476,...,0.020002,0.002297,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
MaritalStatus,-0.095029,0.162070,0.024001,0.056073,-0.014437,0.004053,0.014420,-0.003593,-0.047183,-0.038497,...,0.012492,0.005207,-0.662577,-0.077886,0.010629,0.014708,-0.059986,-0.065822,-0.030915,-0.038570
MonthlyIncome,0.497855,-0.159840,0.034319,0.053130,-0.017014,0.094961,-0.041070,-0.006259,-0.031858,-0.015271,...,-0.027269,-0.017120,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
NumCompaniesWorked,0.299635,0.043494,0.020875,-0.035882,-0.029251,0.126317,-0.008663,0.012594,-0.039147,0.015012,...,-0.010238,-0.014095,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
OverTime,0.028062,0.246118,0.016543,0.007481,0.025514,-0.020322,0.002259,0.070132,-0.041924,-0.003507,...,-0.005433,0.004369,-0.000449,0.012754,-0.079113,-0.027092,-0.011687,-0.029758,-0.012239,-0.041586
PercentSalaryHike,0.003634,-0.013478,-0.029377,-0.007840,0.040235,-0.011111,-0.011214,-0.031701,0.002733,-0.017205,...,1.000000,0.773550,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
PerformanceRating,0.001904,0.002889,-0.026341,-0.024604,0.027110,-0.024539,-0.005614,-0.029548,-0.013859,-0.029071,...,0.773550,1.000000,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
StockOptionLevel,0.037510,-0.137145,-0.016727,-0.012193,0.044872,0.018422,-0.016185,0.003432,0.012716,0.021523,...,0.007528,0.003506,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
TotalWorkingYears,0.680381,-0.171063,0.034226,-0.015762,0.004628,0.148280,-0.027848,-0.002693,-0.046881,-0.005533,...,-0.020608,0.006744,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
TrainingTimesLastYear,-0.019621,-0.059478,0.015240,0.036875,-0.036942,-0.025100,0.049195,-0.019359,-0.038787,-0.015338,...,-0.005221,-0.015579,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
WorkLifeBalance,-0.021490,-0.063939,-0.011256,0.026383,-0.026556,0.009819,0.041191,0.027627,-0.002753,-0.014617,...,-0.003280,0.002572,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
YearsAtCompany,0.311309,-0.134392,-0.014575,0.022920,0.009508,0.069114,-0.018692,0.001458,-0.029747,-0.021355,...,-0.035991,0.003435,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
YearsInCurrentRole,0.212901,-0.160545,-0.011497,0.056315,0.018845,0.060236,-0.010506,0.018007,-0.041483,0.008717,...,-0.001520,0.034986,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
YearsSinceLastPromotion,0.216513,-0.033019,-0.032591,0.040061,0.010029,0.054254,0.002326,0.016194,-0.026985,-0.024184,...,-0.022154,0.017896,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,-0.022636,0.034282,0.014406,0.069065,-0.004130,-0.004999,-0.030599,0.025976,...,-0.011985,0.022827,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

In [18]:
cor = df.corr()
cor_target = abs(cor["PastEmployee"])

In [20]:
cor_target_org = cor["PastEmployee"]

In [21]:
cor_target_org

Age                       -0.159205
PastEmployee               1.000000
BusinessTravel             0.000074
Department                 0.063991
DistanceFromHome           0.077924
Education                 -0.031373
EducationField             0.026846
EnvironmentSatisfaction   -0.103369
Gender                     0.029453
JobInvolvement            -0.130016
JobLevel                  -0.169105
JobRole                    0.067151
JobSatisfaction           -0.103481
MaritalStatus              0.162070
MonthlyIncome             -0.159840
NumCompaniesWorked         0.043494
OverTime                   0.246118
PercentSalaryHike         -0.013478
PerformanceRating          0.002889
StockOptionLevel          -0.137145
TotalWorkingYears         -0.171063
TrainingTimesLastYear     -0.059478
WorkLifeBalance           -0.063939
YearsAtCompany            -0.134392
YearsInCurrentRole        -0.160545
YearsSinceLastPromotion   -0.033019
YearsWithCurrManager      -0.156199
Name: PastEmployee, dtype: float64

In [19]:
cor_target

Age                        0.159205
PastEmployee               1.000000
BusinessTravel             0.000074
Department                 0.063991
DistanceFromHome           0.077924
Education                  0.031373
EducationField             0.026846
EnvironmentSatisfaction    0.103369
Gender                     0.029453
JobInvolvement             0.130016
JobLevel                   0.169105
JobRole                    0.067151
JobSatisfaction            0.103481
MaritalStatus              0.162070
MonthlyIncome              0.159840
NumCompaniesWorked         0.043494
OverTime                   0.246118
PercentSalaryHike          0.013478
PerformanceRating          0.002889
StockOptionLevel           0.137145
TotalWorkingYears          0.171063
TrainingTimesLastYear      0.059478
WorkLifeBalance            0.063939
YearsAtCompany             0.134392
YearsInCurrentRole         0.160545
YearsSinceLastPromotion    0.033019
YearsWithCurrManager       0.156199
Name: PastEmployee, dtype: float64

In [24]:
chosen_features = cor_target[cor_target>0.1]

In [25]:
chosen_features

Age                        0.159205
PastEmployee               1.000000
EnvironmentSatisfaction    0.103369
JobInvolvement             0.130016
JobLevel                   0.169105
JobSatisfaction            0.103481
MaritalStatus              0.162070
MonthlyIncome              0.159840
OverTime                   0.246118
StockOptionLevel           0.137145
TotalWorkingYears          0.171063
YearsAtCompany             0.134392
YearsInCurrentRole         0.160545
YearsWithCurrManager       0.156199
Name: PastEmployee, dtype: float64

In [30]:
ls1 = list(chosen_features.index.values)
# .index().tolist()

In [31]:
ls1

['Age',
 'PastEmployee',
 'EnvironmentSatisfaction',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'OverTime',
 'StockOptionLevel',
 'TotalWorkingYears',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsWithCurrManager']

In [32]:
df_new = df[ls1]

In [33]:
df_new

,Age,PastEmployee,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MaritalStatus,MonthlyIncome,OverTime,StockOptionLevel,TotalWorkingYears,YearsAtCompany,YearsInCurrentRole,YearsWithCurrManager
0,46,0,2,3,2,2,0,5021,1,1,16,4,2,2
1,37,1,3,3,1,1,0,2073,1,0,7,3,2,2
2,59,0,3,2,5,4,1,18844,0,1,30,3,2,2
3,54,0,4,4,4,4,2,17328,1,0,23,5,3,4
4,26,0,3,3,1,3,1,2942,0,1,8,8,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,45,0,4,3,2,3,2,4850,0,0,8,5,3,1
1466,50,1,4,2,3,1,0,10854,1,1,20,3,2,0
1467,39,0,2,2,4,4,1,12031,0,1,21,20,9,6
1468,26,0,4,2,1,3,2,2966,0,0,5,4,2,0
1469,49,0,4,2,2,2,1,5390,0,0,17,9,6,8

In [35]:
X_feat = df_new.drop(columns=['PastEmployee'])
y = df['PastEmployee']

In [36]:
X_train_feat, X_test_feat, y_train, y_test = train_test_split(X_feat, y, test_size = 0.25, random_state = 42)

In [37]:
LR(X_train_feat, X_test_feat, y_train, y_test)

[[306   0]
 [ 61   1]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91       306
           1       1.00      0.02      0.03        62

    accuracy                           0.83       368
   macro avg       0.92      0.51      0.47       368
weighted avg       0.86      0.83      0.76       368

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [39]:
gaussian(X_train_feat, X_test_feat, y_train, y_test)

[[257  49]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.87       306
           1       0.42      0.58      0.49        62

    accuracy                           0.80       368
   macro avg       0.67      0.71      0.68       368
weighted avg       0.83      0.80      0.81       368

## Scale the dataset

In [40]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

### Standardize the data

In [41]:
std = StandardScaler()
X_std = std.fit_transform(X)

Standard scaler with original data

In [42]:
X_train_std, X_test_std, y_train, y_test = train_test_split(X_std, y, test_size = 0.25, random_state = 42)

In [43]:
LR(X_train_std, X_test_std, y_train, y_test)

[[297   9]
 [ 44  18]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       306
           1       0.67      0.29      0.40        62

    accuracy                           0.86       368
   macro avg       0.77      0.63      0.66       368
weighted avg       0.84      0.86      0.83       368

In [44]:
gaussian(X_train_std, X_test_std, y_train, y_test)

[[255  51]
 [ 23  39]]
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       306
           1       0.43      0.63      0.51        62

    accuracy                           0.80       368
   macro avg       0.68      0.73      0.69       368
weighted avg       0.84      0.80      0.81       368

Standard scaler with serlected features

In [45]:
X_std_feat = std.fit_transform(X_feat)
X_train_std_feat, X_test_std_feat, y_train, y_test = train_test_split(X_std_feat, y, test_size = 0.25, random_state = 42)

In [46]:
LR(X_train_std_feat, X_test_std_feat, y_train, y_test)

[[299   7]
 [ 41  21]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       306
           1       0.75      0.34      0.47        62

    accuracy                           0.87       368
   macro avg       0.81      0.66      0.70       368
weighted avg       0.86      0.87      0.85       368

In [47]:
gaussian(X_train_std_feat, X_test_std_feat, y_train, y_test)

[[255  51]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.41      0.58      0.48        62

    accuracy                           0.79       368
   macro avg       0.66      0.71      0.68       368
weighted avg       0.82      0.79      0.80       368

### Min_Max Scaling

In [48]:
min_max = MinMaxScaler()
X_mm = min_max.fit_transform(X)

In [49]:
X_train_mm, X_test_mm, y_train, y_test = train_test_split(X_mm, y, test_size = 0.25, random_state = 42)

In [50]:
LR(X_train_mm, X_test_mm, y_train, y_test)

[[299   7]
 [ 44  18]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       306
           1       0.72      0.29      0.41        62

    accuracy                           0.86       368
   macro avg       0.80      0.63      0.67       368
weighted avg       0.85      0.86      0.84       368

In [51]:
gaussian(X_train_mm, X_test_mm, y_train, y_test)

[[255  51]
 [ 23  39]]
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       306
           1       0.43      0.63      0.51        62

    accuracy                           0.80       368
   macro avg       0.68      0.73      0.69       368
weighted avg       0.84      0.80      0.81       368

In [52]:
X_mm_feat = min_max.fit_transform(X_feat)
X_train_mm_feat, X_test_mm_feat, y_train, y_test = train_test_split(X_mm_feat, y, test_size = 0.25, random_state = 42)

In [53]:
LR(X_train_mm_feat, X_test_mm_feat, y_train, y_test)

[[299   7]
 [ 43  19]]
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       306
           1       0.73      0.31      0.43        62

    accuracy                           0.86       368
   macro avg       0.80      0.64      0.68       368
weighted avg       0.85      0.86      0.84       368

In [54]:
gaussian(X_train_mm_feat, X_test_mm_feat, y_train, y_test)

[[255  51]
 [ 26  36]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87       306
           1       0.41      0.58      0.48        62

    accuracy                           0.79       368
   macro avg       0.66      0.71      0.68       368
weighted avg       0.82      0.79      0.80       368